name: Build and Deploy Backend + Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Backend build & push
    - name: Build backend image
      run: docker build -t devdashy/genetic-backend:latest ./backend

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push backend image
      run: docker push devdashy/genetic-backend:latest

    # Frontend build & push
    - name: Build frontend image
      run: docker build -t devdashy/genetic-frontend:latest ./frontend

    - name: Push frontend image
      run: docker push devdashy/genetic-frontend:latest

    # Deploy to server
    - name: Deploy on server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull devdashy/genetic-backend:latest
          docker pull devdashy/genetic-frontend:latest

          docker stop backend || true
          docker rm backend || true
          docker run -d --name backend -p 3000:3000 devdashy/genetic-backend:latest

          docker stop frontend || true
          docker rm frontend || true
          docker run -d --name frontend -p 8082:80 devdashy/genetic-frontend:latest
